version: '3'
services:
  postgres:
    image: postgres:${SOFTWARE_VERSION_TAG}
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${SOFTWARE_PASSWORD}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - '172.17.0.1:34523:5432'
  pgadmin4:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${SOFTWARE_PASSWORD}
      PGADMIN_LISTEN_PORT: 443
      PGADMIN_ENABLE_TLS: 1
    ports:
      - "172.17.0.1:34343:443"
    depends_on:
      - postgres
    volumes:
      - ./servers.json:/pgadmin4/servers.json
      - /root/.acme.sh/vm.appdrag.net/fullchain.cer:/certs/server.cert
      - /root/.acme.sh/vm.appdrag.net/vm.appdrag.net.key:/certs/server.key
